import json
import re
from pathlib import Path
from anthropic import AsyncAnthropic
from tools.executor import execute_python
import config

_TOOLS_DIR = Path.home() / ".multi_agent" / "tools"
_REGISTRY = _TOOLS_DIR / "registry.json"

_GEN_PROMPT = """生成一个独立的 Python 工具函数。

工具名称：{name}
功能描述：{description}
参数定义：{parameters}
{extra}

严格要求：
1. 函数签名必须是 `def run(params: dict) -> str`
2. 所有 import 语句写在函数体内部
3. 返回值必须是字符串（结果或错误信息）
4. 包含 try/except 错误处理，异常时返回 "Error: ..." 格式
5. 代码要完整可运行，不要占位符
6. 只输出纯 Python 代码，不要 markdown 代码块，不要任何解释"""


class ToolForge:
    def __init__(self, client: AsyncAnthropic):
        self.client = client
        _TOOLS_DIR.mkdir(parents=True, exist_ok=True)

    async def create(
        self,
        name: str,
        description: str,
        parameters: dict[str, str],
        reason: str = "",
    ) -> dict:
        """生成、校验、持久化一个新工具，返回工具定义。"""
        name = _sanitize_name(name)

        # 已存在则直接返回
        registry = self._load_registry()
        if name in registry:
            return self._make_def(name, registry[name]["description"], registry[name]["parameters"])

        code = await self._generate(name, description, parameters, reason)
        error = _validate_syntax(code)

        if error:
            # 带错误反馈重试一次
            code = await self._generate(name, description, parameters, reason, syntax_error=error)
            error = _validate_syntax(code)
            if error:
                raise ValueError(f"工具 {name} 代码生成失败：{error}")

        self._persist(name, description, parameters, code)
        return self._make_def(name, description, parameters)

    def load_all(self) -> list[dict]:
        """加载所有已保存的动态工具定义。"""
        registry = self._load_registry()
        return [
            self._make_def(name, info["description"], info["parameters"])
            for name, info in registry.items()
        ]

    def get_code(self, name: str) -> str | None:
        path = _TOOLS_DIR / f"{name}.py"
        return path.read_text(encoding="utf-8") if path.exists() else None

    async def _generate(
        self,
        name: str,
        description: str,
        parameters: dict,
        reason: str,
        syntax_error: str = "",
    ) -> str:
        extra_lines = []
        if reason:
            extra_lines.append(f"使用场景：{reason}")
        if syntax_error:
            extra_lines.append(f"上次生成有语法错误，请修正：{syntax_error}")

        prompt = _GEN_PROMPT.format(
            name=name,
            description=description,
            parameters=json.dumps(parameters, ensure_ascii=False),
            extra="\n".join(extra_lines),
        )
        resp = await self.client.messages.create(
            model=config.AGENT_MODEL,
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}],
        )
        code = resp.content[0].text.strip()
        # 去掉可能的 markdown 代码块
        code = re.sub(r"^```(?:python)?\n?", "", code)
        code = re.sub(r"\n?```$", "", code)
        return code.strip()

    def _persist(self, name: str, description: str, parameters: dict, code: str):
        # 保存代码文件
        path = _TOOLS_DIR / f"{name}.py"
        header = f"# Tool: {name}\n# Description: {description}\n# Auto-generated by ToolForge\n\n"
        path.write_text(header + code, encoding="utf-8")

        # 更新 registry
        registry = self._load_registry()
        registry[name] = {"description": description, "parameters": parameters}
        _REGISTRY.write_text(json.dumps(registry, ensure_ascii=False, indent=2), encoding="utf-8")

    def _load_registry(self) -> dict:
        if _REGISTRY.exists():
            try:
                return json.loads(_REGISTRY.read_text(encoding="utf-8"))
            except Exception:
                return {}
        return {}

    @staticmethod
    def _make_def(name: str, description: str, parameters: dict[str, str]) -> dict:
        props = {k: {"type": v, "description": k} for k, v in parameters.items()}
        return {
            "name": name,
            "description": description,
            "input_schema": {
                "type": "object",
                "properties": props,
                "required": list(parameters.keys()),
            },
            "_dynamic": True,
        }


def _sanitize_name(name: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9_一-鿿]", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    return name[:64] or "tool"


def _validate_syntax(code: str) -> str:
    try:
        compile(code, "<tool>", "exec")
        return ""
    except SyntaxError as e:
        return str(e)
